routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
/**
 * auth user routes
 */
Auth::routes();

/**
 * home route
 */
Route::get('/home', 'HomeController@index')->name('home');

/**
 * All admin routes
 */
Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function () {
    Route::get('/', 'AdminController@index')->name('admin');
    // Blog model routes
    Route::group(['prefix' => 'blogs' , 'middleware' => 'auth'], function () {
    //  Soft delete future
        Route::get('/bin', 'BlogController@bin')->name('blogs.bin');
        Route::get('/bin/{id}/restore', 'BlogController@restore');
        Route::delete('/bin/{id}/remove', 'BlogController@removePermanent');

        Route::get('/', 'BlogController@index')->name('blogs.index');
        Route::get('create', 'BlogController@create')->name('blogs.create');
        Route::post('store', 'BlogController@store');
        Route::get('{id}', 'BlogController@show')->name('blogs.show');
        Route::get('{id}/edit', 'BlogController@edit')->name('blogs.update');
        Route::patch('{id}', 'BlogController@update');
        Route::delete('{id}', 'BlogController@destroy');
        Route::get('{id}/change_status','BlogController@publish' )->name('blogs.change_status');
    });
    //  category route resource
    Route::resource('categories', 'CategoryController')->middleware(['auth']);

    //  tag route resource
    Route::resource('tags', 'TagController')->middleware(['auth']);
});


//Route::resource('blogs', 'BlogController');

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Blog extends Model
{
    // soft delete
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = ['title', 'body', 'slug', 'meta_title', 'meta_description', 'status'];

    /**
     * many to many with category model
     */
    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    /**
     * many to many with tag model
     */
    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    /**
     * one to many with user model
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Blog;
use App\Category;
use App\Tag;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use Intervention\Image\Facades\Image;

class BlogController extends Controller
{

    /**
     * Pagination limit
     */
    const PAGE_LIMIT = 10;

    /**
     * Uploaded images folder path
     */
    const IMAGES_PATH = "uploads". DIRECTORY_SEPARATOR;
    const BLOG_IMAGES_PATH = self::IMAGES_PATH . 'featured_images' . DIRECTORY_SEPARATOR;
    const BLOG_THUMBNAILS_PATH = self::IMAGES_PATH . 'thumbnails' . DIRECTORY_SEPARATOR;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        $blogs = DB::table('blogs')->orderBy('created_at', 'desc')->where('deleted_at',NULL)->paginate(10);
        $blogs = Blog::latest()->paginate(self::PAGE_LIMIT);
        return view('admin.blogs.index', compact('blogs'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::get();
        $tags = Tag::get();
        if($categories->count() == 0){
            Session::flash('noCategory', "U have to create category first");
            return redirect()->route('categories.create');
        }
        return view('admin.blogs.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $blog = new Blog();
        $blog->title = $request->input('title');
        $blog->slug = str_slug($request->input('title'));
        $blog->body = $request->input('body');
        // SEO meta data
        $blog->meta_title = str_limit($request->input('title'), 55);
        $blog->meta_description = str_limit($request->input('body'), 155);
        // User
        $blog->user_id = Auth::user()->id;
        $roles = [
            'title' => 'required | min : 3',
            'body' => 'required',
        ];
        $this->validate($request, $roles);
        //Image handling
        if($request->hasFile('featured_image')){
            // 01- get the image form the request
            $image = $request->file('featured_image');
            // 02- rename the image
            $image_name = Carbon::now()->timestamp. '_' .$image->getClientOriginalName();
            /**
             * CREATE THUMBNAIL FROM FEATURED IMAGE via intervention package
             */
            $thumbnail = 'thumbnail_'.$image_name;
            $resizedImage = Image::make($image)->resize(100,null, function($constraint){
                $constraint->aspectRatio();
            });
            $resizedImage->save(public_path('/') . self::BLOG_THUMBNAILS_PATH . $thumbnail,100);
            $blog->thumbnail = $thumbnail;
            /**
             * Handle the image with image Intervention package OR via laravel default
             */
            // 03- upload the image
            // Via image intervention package functionality
            //Image::make($image)->save(public_path('/') . self::IMAGES_PATH . $image_name);
            // Via laravel default functionality
            $image->move(public_path('/'). self::BLOG_IMAGES_PATH, $image_name);
            // 04- save the image in the database
            $blog->featured_image = $image_name;

        }
        // Create record
        if ($blog->save()){
            /**
             * sync blog with categories and tags:: this should be after save or create method
             */
            if($request->has('category_id')){
                $blog->categories()->sync($request->category_id);
            }
            if($request->has('tag_id')){
                $blog->tags()->sync($request->tag_id);
            }
            return redirect()->route('blogs.index');
        }
        else{
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $blog = Blog::findOrFail($id);
        return view('admin.blogs.show')->with('blog', $blog);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $allCategories = Category::latest()->get();
        $allTags = Tag::latest()->get();
        $blog = Blog::findOrFail($id);
        return view('admin.blogs.update', compact('blog', 'allCategories', 'allTags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, $id)
    {
        $blog = Blog::findOrFail($id);
        $blog->title = $request->input('title');
        $blog->body = $request->input('body');

        //Image handling
        if($request->hasFile('featured_image')){
            // 01- get the image form the request
            $image = $request->file('featured_image');
            // 02- rename the image
            $image_name = Carbon::now()->timestamp. '_' .$image->getClientOriginalName();
            /**
             * Handle the image with image Intervention package OR via laravel default
             */
            // 03- upload the image
            // Via image intervention package functionality
            //Image::make($image)->save(public_path('/') . self::IMAGES_PATH . $image_name);
            // Via laravel default functionality
            $image->move(public_path('/'). self::BLOG_IMAGES_PATH, $image_name);


            // 04- Remove the old image
            if($blog->featured_image){
                $old_post_img = public_path('/'). self::BLOG_IMAGES_PATH . $blog->featured_image;
                if(file_exists($old_post_img)){
                    unlink($old_post_img);
                }
            }
            // 05- save the new image in the database
            $blog->featured_image = $image_name;
        }

        if ($blog->save()){
            /**
             * sync blog with category and tags:: this should be after save or create method
             */
            if($request->has('category_id')){
                $blog->categories()->sync($request->category_id);
            }
            return redirect()->route('blogs.index');
        } else {
            return redirect()->back();
        }
    }

    /**
     * move posts to bin
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function destroy($id)
    {
        $blog = Blog::findOrFail($id);
        $blog->delete();
        return redirect()->route('blogs.bin');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * trash the posts
     */

    public function bin()
    {
        $deletedBlogs = Blog::onlyTrashed()->get();
        return view('admin.blogs.bin', compact('deletedBlogs'));
    }

    /**
     * restore trashed posts
     */

    public function restore($id)
    {
        $restoredBlogs = Blog::onlyTrashed()->findOrFail($id);
        $restoredBlogs->restore();
        return redirect()->route('blogs.index');

    }

    /**
     * delete the trashed posts permanently
     */

    public function removePermanent($id)
    {
        $trashedBlog = Blog::onlyTrashed()->findOrFail($id);
        // Delete post and image (if exists)
        if($trashedBlog->featured_image !== null){
            $post_image = public_path("/"). self::BLOG_IMAGES_PATH .$trashedBlog->featured_image  ;
            if(file_exists($post_image)){
                unlink($post_image);
            }
        }
        $trashedBlog->forceDelete();

        return redirect()->back();
    }

    public function publish($id)
    {
        $publishedBlog = Blog::findOrFail($id);
        if($publishedBlog->status != true){
            $publishedBlog->status = true;
            $publishedBlog->update(['status', $publishedBlog->status, 'updated_at' => Carbon::now()]);
            return back();
        } else {
            $publishedBlog->status = false;
            $publishedBlog->update(['status', $publishedBlog->status]);
            return back();
        }
    }
}

resources/views/admin/blogs/bin.blade.php
@extends('layouts.admin')
@section('title' , 'Trashed posts')
@section('content')
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>id</th>
                <th>title</th>
                <th>body</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            @if($deletedBlogs->count() == 0)
                <tr><td><h1>There is no content</h1></td></tr>
            @else
            @foreach($deletedBlogs as $blog)
                <tr>
                    <td>{{ $blog->id }}</td>
                    <td>{{$blog->title}}</td>
                    <td><p>{{str_limit($blog->body, 100, '...')}}</p></td>
                    <td>{!! Form::open(['method' => 'DELETE', 'action' => ['BlogController@removePermanent', $blog->id]]) !!}
                        <button type="submit" class="btn btn-danger"><i class="fa fa-times"></i></button>
                        {!! Form::close() !!}
                    </td>
                    <td><a href="{!! action('BlogController@restore', ['id' => $blog->id]) !!}" class="btn btn-success"><i class="fa fa-check-circle"></i></a></td>
                </tr>
            @endforeach
             @endif
            </tbody>
        </table>
    </div>
@endsection

resources/views/admin/blogs/create.blade.php
@extends('layouts.admin')
@section('title' , 'New post')
@section('content')
{{-- Tinymce editor--}}
@include('partials._tinymce_editor')
    {!! Form::open(['method' => 'POST','action' => 'BlogController@store', 'files' => true]) !!}
    {{-- Display validation errors for each field  --}}
    <div class="form-group @if($errors->has('title')) has-error @endif">
    {!! Form::label('title', 'Title'); !!}
    {!! Form::text('title','', ['id' => 'title', 'class' =>'form-control']); !!}
        @if($errors->has('title')) <p class="text-danger">{{ $errors->first('title') }}</p> @endif
    </div>
    {!! Form::label('body', 'body'); !!}
    {{--{!! Form::textarea('body','', ['id' => 'body', 'class' =>'form-control my-editor']); !!}--}}
    <textarea name="body" class="form-control my-editor" id="body">{!! old('body') !!}</textarea>
    <div class="form-group">
        <label>Categories</label><br >
        @foreach($categories as $category)
            <input type="checkbox" name="category_id[]" value="{{ $category->id }}">
            <label class="checkbox-inline">{{ $category->name }}</label>
        @endforeach
    </div>
    <div class="form-group">
        <label>Tags</label>
        <select name="tag_id[]" multiple class="form-control">
            @foreach($tags as $tag)
                <option value="{{ $tag->id }}">{{ $tag->name }}</option>
            @endforeach
        </select>
    </div>
<button type="reset" class="btn btn-default">Reset</button>

    <div class="form-group">
        <label>Featured image</label>
        <input type="file" name="featured_image" class="form-control">
    </div>

    {!! Form::submit('Create' ,['class' => 'btn btn-primary']); !!}
    {!! Form::close() !!}
@endsection

resources/views/admin/blogs/index.blade.php
@extends('layouts.admin')
@section('title' , 'Posts')
@section('content')
    {{--<div class="col-lg-12">--}}
        <a href="{{ route('blogs.create') }}" class="btn btn-primary">Create new blog</a>
    {{--</div>--}}
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Featured image</th>
                <th>Title</th>
                <th>Body</th>
                <th>Categories</th>
                <th>tags</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @if($blogs->count() == 0)
                <tr><td><h1>There is no content</h1></td></tr>
            @else
            @foreach($blogs as $blog)
                <tr>
                    <td>
                        @if($blog->featured_image)
                            <img  src="/uploads/thumbnails/{{ $blog->thumbnail }}" alt="{{ $blog->title }}">
                         @else
                            <img width="100" src="/uploads/featured_images/no_image.jpg" alt="{{ $blog->title }}">
                        @endif    
                    </td>
                    <td>{{$blog->title}}</td>
                    <td><p>{!! str_limit($blog->body, 50, '...')!!}</p></td>
                    <td>
                        @if($blog->categories->count() > 0)
                        @foreach($blog->categories as $category)
                            <a href="{{ route('categories.show', $category->slug) }}">{{ $category->name }}</a> &nbsp;
                        @endforeach
                        @else
                            <strong>Not categorized</strong>
                        @endif
                    </td>
                    <td>
                        @if($blog->tags->count() > 0)
                            @foreach($blog->tags as $tag)
                                {{--{{ route('categories.show', $category->slug) }}--}}
                                {{ $tag->name }}
                            @endforeach
                        @else
                            <strong>No tags</strong>
                        @endif
                    </td>
                    <td>
                        @if($blog->status !=true)
                            <a href="{{ route('blogs.change_status', $blog->id) }}" class="btn btn-danger btn-xs">pending</a>
                        @else
                            <a href="{{ route('blogs.change_status', $blog->id) }}" class="btn btn-success btn-xs" >published</a>
                        @endif
                    </td>
                    <td>{!! Form::open(['method' => 'DELETE', 'action' => ['BlogController@destroy', $blog->id]]) !!}
                        <button type="submit" class="btn btn-danger"><i class="fa fa-times"></i></button>
                        {!! Form::close() !!}
                    </td>
                    <td><a href="{!! action('BlogController@edit', ['id' => $blog->id]) !!}" class="btn btn-success"><i class="fa fa-check-circle"></i></a></td>
                    <td><a href="{!! action('BlogController@show', $blog->id) !!}" class="btn btn-primary"><i class="fa fa-eye"></i></a></td>
                </tr>
            @endforeach
             @endif
            </tbody>
        </table>
    </div>
    {{-- Pagination links --}}
{{ $blogs->links() }}
@endsection

resources/views/admin/blogs/show.blade.php
@extends('layouts.admin')

@section('title' , $blog->title)
@section('content')
    <div class="container-fluid">
        <div class="col-md-12">
            @if($blog->featured_image)
                <img class="img-responsive featured-img" src="/uploads/featured_images/{{ $blog->featured_image ?? "" }}" alt="{{ str_limit($blog->title, 50) }}">
            @endif    
        </div>
    </div>
    <p><b>Created by: {{ $blog->user->name }}</b></p>
    <p>{!! $blog->body !!}</p>
    <div class="col-md-12">
        <a href="{{ route('blogs.index') }}" class="btn btn-lg btn-link btn-primary">Back</a>
        <br>
        <strong>Categories : </strong>
        @foreach($blog->categories as $category)
        <a href="{{ route('categories.show', $category->slug) }}">{{ $category->name }}</a>
        @endforeach
        <br>
        <strong>Tags : </strong>
        <ul class="">
            @foreach($blog->tags as $tag)
                <li class="list-item"> {{ $tag->name }}</li>
            @endforeach
        </ul>


    </div>
@endsection

resources/views/admin/blogs/update.blade.php
@extends('layouts.admin')
@section('content')
@include('partials._tinymce_editor')
    {{-- Model form binding --}}
    {!! Form::model($blog,['action' => ['BlogController@update',  $blog->id],'files' => true]) !!}
    {{ method_field('PATCH') }}
    {!! Form::label('title', 'Title'); !!}
    {!! Form::text('title',null, ['id' => 'title', 'class' =>'form-control']); !!}
    {!! Form::label('body', 'body'); !!}
    {{--{!! Form::textarea('body',null, ['id' => 'body', 'class' =>'form-control']); !!}--}}
    <textarea name="body" class="form-control my-editor" id="body">{!! old('body', $blog->body) !!}</textarea>
    <div class="form-group">
        <label>Categories : </label>
        @foreach($allCategories as $category)
            <input type="checkbox" name="category_id[]" value="{{ $category->id }}"
            @if($blog->categories->count() > 0)
                @foreach($blog->categories as $blogCategory)
                    @if($blogCategory->id === $category->id)
                        checked
                    @endif
                @endforeach
            @endif
            >
            <label class="checkbox-inline">{{ $category->name }}</label>
        @endforeach

    </div>
    {{--@if($blog->tags->count() > 0)--}}
        {{--<div class="form-group">--}}
            {{--<label>Tags</label>--}}
            {{--@foreach($allTags as $tag)--}}
            {{--<input type="checkbox" name="tag_id[]" value="{{ $tag->id }}"--}}
               {{--@foreach($blog->tags as $blogTag) checked @endforeach--}}
            {{-->--}}
                {{--<label class="checkbox-inline">{{ $tag->name }}</label>--}}
            {{--@endforeach--}}
        {{--</div>--}}
    {{--@endif--}}

    <div class="form-group">
        <div class="col-md-12">
            <div class="col-md-9">
                <label>Featured image</label>
                <input type="file" name="featured_image" class="form-control">
            </div>
            <div class="col-md-3">
                @if($blog->featured_image)
                    <img width="100" src="/uploads/featured_images/{{ $blog->featured_image }}" alt="{{ $blog->title }}">
                @else
                    <img width="100" src="/uploads/featured_images/no_image.jpg" alt="{{ $blog->title }}">
                @endif
            </div>
        </div>
    </div>
    <div class="form-group">
        {!! Form::submit('Edit' ,['class' => 'btn btn-success']); !!}
    </div>
    {!! Form::close() !!}

    <div class="form-group">
        <a href="{{ URL::previous() }}" class="btn btn-lg btn-link btn-primary">Back</a>
    </div>

@endsection