routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
/**
 * auth user routes
 */
Auth::routes();

/**
 * home route
 */
Route::get('/home', 'HomeController@index')->name('home');

/**
 * All admin routes
 */
Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function () {
    Route::get('/', 'AdminController@index')->name('admin');
    // Blog model routes
    Route::group(['prefix' => 'blogs' , 'middleware' => 'auth'], function () {
    //  Soft delete future
        Route::get('/bin', 'BlogController@bin')->name('blogs.bin');
        Route::get('/bin/{id}/restore', 'BlogController@restore');
        Route::delete('/bin/{id}/remove', 'BlogController@removePermanent');

        Route::get('/', 'BlogController@index')->name('blogs.index');
        Route::get('create', 'BlogController@create')->name('blogs.create');
        Route::post('store', 'BlogController@store');
        Route::get('{id}', 'BlogController@show')->name('blogs.show');
        Route::get('{id}/edit', 'BlogController@edit')->name('blogs.update');
        Route::patch('{id}', 'BlogController@update');
        Route::delete('{id}', 'BlogController@destroy');
        Route::get('{id}/change_status','BlogController@publish' )->name('blogs.change_status');
    });
    //  category route resource
    Route::resource('categories', 'CategoryController')->middleware(['auth']);

    //  tag route resource
    Route::resource('tags', 'TagController')->middleware(['auth']);
});


//Route::resource('blogs', 'BlogController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'slug', 'body', 'cat_image'];

    /**
     * many to many with blog model
     */
    public function blogs()
    {
        return $this->belongsToMany(Blog::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    const IMAGES_PATH = "uploads". DIRECTORY_SEPARATOR;
    const CATEGORY_IMAGES_PATH = self::IMAGES_PATH . 'category_images' . DIRECTORY_SEPARATOR;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::latest()->get();
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Get all fields from the request
        $input = $request->all();
        // Image handling
        if($request->hasFile('cat_image')){
            // get the image input from the request
            $image = $request->file('cat_image');
            // rename the image
            $image_name = uniqid() . $image->getClientOriginalName();
            // move the image to the target folder
            $image->move(public_path('/'). self::CATEGORY_IMAGES_PATH, $image_name);
            // save the image in the DB
            $input['cat_image'] = $image_name;
        }
        // create the slug
        $input['slug'] =  str_slug($request['name'], '-');

        // create other fields
        if(Category::create($input)){
            return redirect()->route('categories.index');
        } else {
            return back();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $category = Category::where('slug', $slug)->first();
        return view('admin.categories.show', ['category' => $category]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('admin.categories.update', compact('category'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);
        $category->name = $request['name'];
        $category->slug = str_slug($request['name'], '-');
        $category->body = $request['body'];
        if($request->hasFile('cat_image')){
            // 01- get the image
            $image = $request->file('cat_image');;
            // 20- rename the image
            $cat_image_name = uniqid() . $image->getClientOriginalName();

            // 03- move the image to target folder
            $image->move(public_path('/'). self::CATEGORY_IMAGES_PATH, $cat_image_name );

            // 04- Remove the old image
            if($category->cat_image){
                $old_cat_img = public_path('/'). self::CATEGORY_IMAGES_PATH . $category->cat_image;
                if(file_exists($old_cat_img)){
                    unlink($old_cat_img);
                }
            }
            // 05 - save the image in the database
            $category->cat_image = $cat_image_name;
        }
        if($category->save()){
            return redirect()->route('categories.index');
        } else {
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        if($category->cat_image !== null ){
            $cat_image = public_path('/' . self::CATEGORY_IMAGES_PATH . $category->cat_image);
            if(file_exists($cat_image)){
                unlink($cat_image);
            }
        }
        $category->delete();
        return redirect()->route('categories.index');
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')
@section('title' , 'New category')
@section('content')
{{--  Tiny editor  --}}
@include('partials._tinymce_editor')
    <form action="{{ action('CategoryController@store') }}" method="POST" enctype="multipart/form-data">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name">
        </div>
        <div class="form-group">
            <label for="body">Body</label>
            <textarea name="body" id="body" cols="30" rows="10" class="form-control my-editor"></textarea>
        </div>
        <div class="form-group">
            <label for="cat_image">Image</label>
            <input type="file" class="form-control" id="cat_image" name="cat_image">
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
        {{ csrf_field() }}
    </form>


@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')
@section('title' , 'Categories')
@section('content')
    <a href="{{ route('categories.create') }}" class="btn btn-primary">Create new category</a>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>id</th>
                <th>slug</th>
                <th>name</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            @if($categories->count() == 0)
                <tr><td><h1>There is no content</h1></td></tr>
            @else
            @foreach($categories as $category)
                <tr>
                    <td>{{ $category->id }}</td>
                    <td>{{$category->slug}}</td>
                    <td>{{$category->name}}</td>
                    <td>{!! Form::open(['method' => 'DELETE', 'action' => ['CategoryController@destroy', $category->id]]) !!}
                        <button type="submit" class="btn btn-danger"><i class="fa fa-times"></i></button>
                        {!! Form::close() !!}
                    </td>
                    <td><a href="{!! action('CategoryController@edit',  $category->id) !!}" class="btn btn-success"><i class="fa fa-check-circle"></i></a></td>
                    <td><a href="{!! action('CategoryController@show', $category->slug) !!}" class="btn btn-primary"><i class="fa fa-eye"></i></a></td>
                </tr>
            @endforeach
             @endif
            </tbody>
        </table>
    </div>
    {{-- Pagination links --}}
{{--{{ $categories->links() }}--}}
@endsection

resources/views/admin/categories/show.blade.php
@extends('layouts.admin')
@section('title' , $category->name)
@section('content')
    <div class="col-xs-12">
        <img src="/uploads/category_images/{{ $category->cat_image }}" alt="{{ $category->name }}" class="img-responsive">
    </div>
    <div class="col-xs-12">
        {!! $category->body !!}
    </div>
    <div class="col-md-3">
        <a href="{{ URL::previous() }}" class="btn btn-lg  btn-primary">Back</a>
        <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-lg b btn-warning">Edit</a>
    </div>

@endsection

resources/views/admin/categories/update.blade.php
@extends('layouts.admin')
@section('content')
    {{--Tiny editor --}}
    @include('partials._tinymce_editor')
    {{-- Model form binding --}}
    {!! Form::model($category,['action' => ['CategoryController@update',  $category->id], 'files' => true]) !!}
    {{ method_field('PATCH') }}
    {!! Form::label('name', 'name'); !!}
    {!! Form::text('name',null, ['id' => 'title', 'class' =>'form-control']); !!}
    <textarea name="body" class="form-control my-editor" id="body">{!! old('body', $category->body) !!}</textarea>
    <div class="form-group">
        <div class="col-md-12">
            <div class="col-md-9">
                <label>Category image</label>
                <input type="file" name="cat_image" class="form-control">
            </div>
            <div class="col-md-3">
                @if($category->cat_image)
                    <img width="100" src="/uploads/category_images/{{ $category->cat_image }}" alt="{{ $category->title }}">
                @else
                    <img width="100" src="/uploads/featured_images/no_image.jpg" alt="{{ $category->title }}">
                @endif
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        {!! Form::submit('Edit' ,['class' => 'btn btn-success']); !!}
    </div>
    {!! Form::close() !!}

    <div class="col-md-3">
        <a href="{{ URL::previous() }}" class="btn btn-lg btn-link btn-primary">Back</a>
    </div>

@endsection